### PR TITLE
Replacing `Dialog.Overlay` with regular `div`.

### PR DESCRIPTION
**Pull request by irsyadadl**
Bump headless ui version from `v1.5` to `v1.7`. And since headless ui entered version `1.6`, this is no longer needed.

The references can be found [here](https://tailwindcss.com/blog/2022-05-23-headless-ui-v1-6-tailwind-ui-team-management#scrollable-dialog-improvements).

### CODE REVIEW

**Comment by ozziexsh** [comment]
hey thanks for bringing this up!

according to that blog post being linked we should also add the `<Dialog.Panel>` component so we can retain the click-outside functionality

do you mind adding that in?

**Review by irsyadadl — COMMENTED** [review]
Change `div` to `Dialog.Panel`.

**Comment by irsyadadl** [comment]
Just to be clear, I will make it simple, wait until the last pull request.

**Comment by ozziexsh** [comment]
hey - going to close this for now as there are too many unrelated changes. feel free to submit another pr if you'd like to see this go through

**Pull request closed without merging**
